# -*- coding: utf-8 -*-
"""lr1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OFDve57cGiafpHnOrZm21Q2NDVgwbjZk
"""

import copy
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

def filter2d(image_array, kernel_array):

    result = np.zeros_like(image_array)
    copy_image = copy.deepcopy(image_array)

    for i in range(kernel_array.shape[0]+1):
        copy_image = np.pad(copy_image, [(0, 1), (0, 1)], mode='constant')

    for x in range(image.shape[0]):
        for y in range(image.shape[1]):
            result[x][y] = (np.array(copy_image[x:(x+kernel_array.shape[0]), y: (y+kernel_array.shape[1])])
                            * np.array(kernel_array)).sum()

    return result

image = cv2.imread('eye1.jpeg',0)

image

cv2_imshow(image)

"""Roberts"""

kernel_Roberts_y = np.array([[0, -1],
                             [1, 0]])
kernel_Roberts_x = np.array([[-1, 0],
                             [0, 1]])

"""Sobel"""

kernel_Sobel_x = np.array([[-10, 0, 1],
                           [-2, 0, 2],
                           [-10, 0, 1]])
kernel_Sobel_y = np.array([[1, 2, 1],
                           [0, 0, 0],
                           [-1, -2, -1]])

"""Filtering"""

output = filter2d(image, kernel_Roberts_x)

"""Results"""

cv2_imshow(output)
